spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop # test 부분을 자신이 원하는 것으로 바꾸시면 됩니다.
    username: sa # username과 password는 자신의 설정에 맞게
    password:
    driver-class-name: org.h2.Driver

springdoc:
  swagger-ui:
    path: '/swagger-ui-custom.html'
    operationsSorter: method
  version: 'v1'
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  model-and-view-allowed: true