create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    login_id varchar(255),
    login_pwd varchar(255),
    role int,
    primary key (id)
);

create table post
(
    id bigint generated by default as identity,
    user_id bigint,
    category_id int,
    title varchar(255),
    content varchar(255),
    views bigint default 0,
    recommended bigint default 0,
    createdAt datetime DEFAULT current_timestamp,
    primary key (id),
    FOREIGN key(user_id) references member(id) ON UPDATE CASCADE
);

