drop table if exists post CASCADE;
-- post 테이블 생성
create table post
(
    id bigint generated by default as identity,
    title varchar(50),
    content varchar(200),
    primary key (id)
);
-- post 데이터 삽입
insert into post(title, content) values('게시물1', '안녕하세요');
insert into post(title, content) values('게시물2', '안녕');
-- post 테이블 조회
select * from post;
-- member 테이블 생성(user라는 이름으로 생성 안됨)
drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    login_id varchar(10),
    login_pw varchar(20),
    nickname varchar(20),
    email varchar(40),
    phone varchar(15),
    role int,
    primary key (id)
);
-- member 데이터 삽입
insert into member(login_id, login_pw, nickname, email, phone, role) values('member1', 'pw1', '닉네임1', 'eamil1@naver.com', '010-1111-1111', 0);
insert into member(login_id, login_pw, nickname, email, phone, role) values('member2', 'pw2', '닉네임2', 'eamil2@naver.com', '010-2222-2222', 0);
insert into member(login_id, login_pw, nickname, email, phone, role) values('member3', 'pw3', '닉네임3', 'eamil3@naver.com', '010-3333-3333', 0);
-- member 테이블 조회
select * from member;